# Site Settings
encoding: UTF-3
exclude: ["*.gem", "*.gemspec", "Gemfile", "Gemfile.lock", "node_modules", "Rakefile", "starter-kit", "vendor"]
lang: en # Language code as defined in _data/i18n.yml. en, en-gb, en-us, zh, zh-cn, zh-tw etc.
permalink: /blog/:year/:month/:day/:title/

whitelist: [jekyll-feed, jekyll-redirect-from, jekyll-seo-tag, jekyll-sitemap]
plugins:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap

markdown: kramdown
kramdown:
  auto_id_prefix: 'heading-'
  smart_quotes: ["apos", "apos", "quot", "quot"]
  toc_levels: 1..3

sass:
  style: compressed

# Site Data
url: # the base hostname & protocol for your site, e.g. http://example.com
baseurl: # the subpath of your site, e.g. /blog
title: LA CONSTRUCTORA del Oeste 
description: "AQUÍ ROBERTO ANDRADA QUIERE HACER PRESENTE LA INVITACIÓN A QUE UD INVIERTA EN LA CONSTRUCCIÓN, PARA ESTO LLAME QUE SE LO ASESORA 11 6227-2399"
keywords: 'jekyll,theme,gem-based,blog'
author: @tecnicoinformaticocorrientes
  name: Daniel Britez
  job_title: Tecnico Informatico y analista junior en Ciberseguridad
  location: Ciudad Autónoma de Buenos Aires
  email: tecnicoinformaticocorrientes@gmail.com
  social_links:
    - name: facebook
      url: https://www.facebook.com/tecnicoinformaticocorrientes
    - name: github
      url: https://github.com/tecnicoinformaticocorrientes
    - name: instagram
      url: https://www.instagram.com/tecnicoinformaticocorrientes/
    - name: linkedin
      url:
    - name: whatsapp
      url:  https://wa.me/5493795308585
    - name: twitter
      url: 
    - name: vk
      url:
home:
  section1: <h1>LA CONSTRUCTORA del Oeste</h1>
  section2: <h2>AQUÍ ROBERTO ANDRADA QUIERE HACER PRESENTE LA INVITACIÓN A QUE UD INVIERTA EN LA CONSTRUCCIÓN, PARA ESTO LLAME QUE SE LO ASESORA 11 6227-2399</h2>
  section3: <div class="social-links"><a class="ico-github btn" href="https://github.com/tecnicoinformaticocorrientes" title="View on GitHub"></a></div>
blog:
  cc_license: http://creativecommons.org/licenses/by-sa/4.0/ # A link to CC License of your choice.
  cc_license_image: /assets/images/theme/cc-by-sa.png # An image of your CC License. 
    footer_content : AQUÍ ROBERTO ANDRADA QUIERE HACER PRESENTE LA INVITACIÓN A QUE UD INVIERTA EN LA CONSTRUCCIÓN, PARA ESTO LLAME QUE SE LO ASESORA 11 6227-2399 <a href="http://jekyllrb.com/"> Jekyll </a> theme.

disqus:
  shortname: # e.g. yizeng
  public_key: # e.g. ULZ0b9TFefCUJHKQd4JCKv2v3u27YoG7YG8zXPewkWrT333Z0Se9YnxLzoV6VM8W
google_tag_manager: # e.g. 'GTM-KCQJXZ8F'
addthis_public_id: # AddThis sharing plugin. See http://www.addthis.com/. E.g. ra-53329e27694534j5 

paths:
  home: /
  blog: /blog/
  categories: /blog/categories/
  tags: /blog/tags/
